2017-10-14 13:42:37,673 DEBUG    root            Loaded Command Group: ['gcloud', 'projects']
2017-10-14 13:42:37,735 DEBUG    root            Loaded Command Group: ['gcloud', 'projects', 'describe']
2017-10-14 13:42:37,736 DEBUG    root            Running gcloud.projects.describe with Namespace(_deepest_parser=ArgumentParser(prog='gcloud.projects.describe', usage=None, description='Shows metadata for a project given a valid project ID.\n\nThis command can fail for the following reasons:\n* The project specified does not exist.\n* The active account does not have permission to access the given project.\n\n## EXAMPLES\n\nThe following command prints metadata for a project with the ID\n`example-foo-bar-1`:\n\n  $ {command} example-foo-bar-1', version=None, formatter_class=<class 'argparse.HelpFormatter'>, conflict_handler='error', add_help=False), _specified_args={'id': 'PROJECT_ID', 'format': '--format'}, account=None, authority_selector=None, authorization_token_file=None, calliope_command=<googlecloudsdk.calliope.backend.Command object at 0x7f94d97bc8d0>, command_path=['gcloud', 'projects', 'describe'], configuration=None, credential_file_override=None, document=None, flatten=None, format='value(projectNumber)', h=None, help=None, http_timeout=None, id='deft-advice-177704', log_http=None, project=None, quiet=None, trace_email=None, trace_log=None, trace_token=None, user_output_enabled=None, verbosity='warning', version=None).
2017-10-14 13:42:37,882 DEBUG    root            HttpError in projects API call.
Traceback (most recent call last):
  File "/tools/google-cloud-sdk/lib/googlecloudsdk/api_lib/cloudresourcemanager/projects_api.py", line 53, in Get
    projectId=project_ref.projectId))
  File "/tools/google-cloud-sdk/lib/googlecloudsdk/third_party/apis/cloudresourcemanager/v1/cloudresourcemanager_v1_client.py", line 630, in Get
    config, request, global_params=global_params)
  File "/tools/google-cloud-sdk/lib/third_party/apitools/base/py/base_api.py", line 723, in _RunMethod
    return self.ProcessHttpResponse(method_config, http_response, request)
  File "/tools/google-cloud-sdk/lib/third_party/apitools/base/py/base_api.py", line 729, in ProcessHttpResponse
    self.__ProcessHttpResponse(method_config, http_response, request))
  File "/tools/google-cloud-sdk/lib/third_party/apitools/base/py/base_api.py", line 599, in __ProcessHttpResponse
    http_response.request_url, method_config, request)
HttpError: HttpError accessing <https://cloudresourcemanager.googleapis.com/v1/projects/deft-advice-177704?alt=json>: response: <{'status': '403', 'content-length': '818', 'x-xss-protection': '1; mode=block', 'x-content-type-options': 'nosniff', 'transfer-encoding': 'chunked', 'vary': 'Origin, X-Origin, Referer', 'server': 'ESF', '-content-encoding': 'gzip', 'cache-control': 'private', 'date': 'Sat, 14 Oct 2017 13:42:37 GMT', 'x-frame-options': 'SAMEORIGIN', 'content-type': 'application/json; charset=UTF-8'}>, content <{
  "error": {
    "code": 403,
    "message": "Google Cloud Resource Manager API has not been used in project deft-advice-177704 before or it is disabled. Enable it by visiting https://console.developers.google.com/apis/api/cloudresourcemanager.googleapis.com/overview?project=deft-advice-177704 then retry. If you enabled this API recently, wait a few minutes for the action to propagate to our systems and retry.",
    "status": "PERMISSION_DENIED",
    "details": [
      {
        "@type": "type.googleapis.com/google.rpc.Help",
        "links": [
          {
            "description": "Google developers console API activation",
            "url": "https://console.developers.google.com/apis/api/cloudresourcemanager.googleapis.com/overview?project=deft-advice-177704"
          }
        ]
      }
    ]
  }
}
>
2017-10-14 13:42:37,883 DEBUG    root            (gcloud.projects.describe) Project [deft-advice-177704] does not exist, or you do not have permission to access it.
Traceback (most recent call last):
  File "/tools/google-cloud-sdk/lib/googlecloudsdk/calliope/cli.py", line 712, in Execute
    resources = args.calliope_command.Run(cli=self, args=args)
  File "/tools/google-cloud-sdk/lib/googlecloudsdk/calliope/backend.py", line 758, in Run
    resources = command_instance.Run(args)
  File "/tools/google-cloud-sdk/lib/surface/projects/describe.py", line 46, in Run
    return projects_api.Get(project_ref)
  File "/tools/google-cloud-sdk/lib/googlecloudsdk/api_lib/cloudresourcemanager/projects_api.py", line 55, in Get
    raise projects_util.ConvertHttpError(error)
ProjectAccessError: Project [deft-advice-177704] does not exist, or you do not have permission to access it.
2017-10-14 13:42:37,884 ERROR    root            (gcloud.projects.describe) Project [deft-advice-177704] does not exist, or you do not have permission to access it.
